Dockerization
opendata-mvcr/ontoGrapher pull request #235
Opened 2021-02-16 13:29 UTC by bindeali

## Info:
* Can be merged right away (but most definitely shouldn't right now).
* Dockerization of the app mostly (more info below) conforming to the Architecture document.
* Even though the deploy preview will be built, it won't work (at this stage, this PR is meant for code review only).

## Detailed changes:
The implementation is similar to that of Mission Control's. Two .env files are provided for production and development, but they currently differ in context only. The Components value is different, I have added a `repositoryPath` meta value to `dbServer` and a `realm` meta value to `authServer` (the complete object is below). The reason for including them is detailed in the Architecture document and I expect that this representation will be changed after further discussion. Otherwise, the appropriate values in the code have been replaced to utilize the new values. Dependency versions have also been updated, as the old versions resulted in build failures.

#### Setup:
I used `docker-compose --env-file [.env file] up` to build and deploy the image.

#### Components JSON:
```
{
  "sgovServer": {
    "name": "SGoV Service",
    "url": "https://kbss.felk.cvut.cz/sgov-server",
    "meta": {}
  },
  "dbServer": {
    "name": "A graph database",
    "url": "http://192.168.1.108:7200",
    "meta": {
		"repositoryPath": "/repositories/testOG"
	}
  },
  "authServer": {
    "name": "OIDC Authentication Service",
    "url": "http://192.168.1.108:8080/auth/",
    "meta": {
		"realm": "kodi-dev"
	}
  },
  "ontographer": {
    "name": "ontoGrapher",
    "url": "https://slovní­k.gov.cz/modelujeme/v-nástroji/ontographer",
    "meta": {
      "workspacePath": "?workspace=%WORKSPACE_IRI%"
    }
  },
  "termitServer": {
    "name": "TermIT backend",
    "url": "https://example.com/termit-backend",
    "meta": {}
  },
  "termit": {
    "name": "TermIT",
    "url": "https://slovní­k.gov.cz/modelujeme/v-nástroji/termit",
    "meta": {
      "workspacePath": "#vocabularies?workspace=%WORKSPACE_IRI%"
    }
  },
  "missionControl": {
    "name": "Mission Control",
    "url": "https://example.com/mission-control",
    "meta": {}
  },
  "issueTracker": {
    "name": "Issue Tracker",
    "url": "https://github.com/opendata-mvcr/sgov-assembly-line/issues",
    "meta": {
      "newBug": "https://github.com/opendata-mvcr/sgov-assembly-line/issues/new?labels=bug&template=po-adavek-na-opravu.md&title=",
      "newFeature": "https://github.com/opendata-mvcr/sgov-assembly-line/issues/new?labels=enhancement&template=po-adavek-na-novou-funkcionalitu.md&title="
    }
  }
}
```

2021-02-16 14:05 UTC, karelklima reviewed
Some things to discuss - especially the auth realm and how it ties to Keycloak.

Overall the PR looks good. The only thing I'd suggest is to configure your IDE or use some linter / code formatter that would attach newlines at the end of each file (see https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline)

2021-02-24 12:59 UTC, psiotwo submitted a review, later dismissed
lgtm

2021-02-26 11:01 UTC, karelklima requested changes
Correct docker build path and circular dependencies (Variables.ts) need to be resolved before merging.

2021-03-01 09:12 UTC, bindeali commented on Dockerfile
> +RUN npm run build
Added an eslint check in addition to the check.

2021-03-01 09:13 UTC, bindeali commented on src/config/Variables.ts
> +import {getComponentsVariable, getEnvironmentVariable} from "../function/FunctionGetVars";
Separated the environment module(s) into Environment.ts and removed the circular dependency.

2021-03-01 09:13 UTC, bindeali commented on Dockerfile
> +ENV PUBLIC_URL=${PUBLIC_PATH}
Changed the PUBLIC_PATH to "."

2021-03-01 09:14 UTC, bindeali commented on .github/workflows/docker-publish.yml
> +      - name: Log into registry
I have swapped the commands as instructed.

2021-03-01 14:08 UTC, karelklima approved these changes
LGTM

2021-03-02 16:20 UTC, merged